### ISSUE TITLE
code rot

### ISSUE THREAD

**Issue by johndpope** [IBM-Design/ios-animations#3]
<img width="1170" alt="screen shot 2016-04-18 at 3 15 29 pm" src="https://cloud.githubusercontent.com/assets/289994/14616440/6f2e6b50-0578-11e6-93cf-524422253337.png">

**Comment by barlock** [comment]
Change in xcode?

**Comment by johndpope** [comment]
swift 2.2 updates. I submitted a PR.

**Comment by johndpope** [comment]
I'm doing some clean up of old github issues. 
@seejamescode - you should probably considering deleting this repo.
